// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useState, useEffect } from 'react'
import { FiSave, FiX, FiPlus, FiTrash2 } from 'react-icons/fi'

function EditableSection({ sectionKey, sectionTitle, data, onSave, onCancel }) {
  const [formData, setFormData] = useState(data || getDefaultData(sectionKey))
  // Move newSkill state to top level, only used for skills section
  const [newSkill, setNewSkill] = useState('')

  useEffect(() => {
    setFormData(data || getDefaultData(sectionKey))
    // Reset newSkill when switching away from skills section
    if (sectionKey !== 'skills') setNewSkill('')
  }, [data, sectionKey])

  const handleSave = () => {
    onSave(formData)
  }

  const renderForm = () => {
    switch (sectionKey) {
      case 'personalInfo':
        return renderPersonalInfoForm()
      case 'summary':
        return renderSummaryForm()
      case 'experience':
        return renderExperienceForm()
      case 'education':
        return renderEducationForm()
      case 'skills':
        return renderSkillsForm()
      case 'certifications':
        return renderCertificationsForm()
      case 'projects':
        return renderProjectsForm()
      default:
        return <div>Unknown section</div>
    }
  }

  const renderPersonalInfoForm = () => (
    <div className="form-grid">
      <div className="form-group">
        <label className="form-label">Full Name</label>
        <input
          type="text"
          className="form-input"
          value={formData.name || ''}
          onChange={(e) => setFormData({ ...formData, name: e.target.value })}
          placeholder="Enter your full name"
        />
      </div>
      <div className="form-group">
        <label className="form-label">Email</label>
        <input
          type="email"
          className="form-input"
          value={formData.email || ''}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          placeholder="your.email@example.com"
        />
      </div>
      <div className="form-group">
        <label className="form-label">Phone</label>
        <input
          type="tel"
          className="form-input"
          value={formData.phone || ''}
          onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
          placeholder="+1 (555) 123-4567"
        />
      </div>
      <div className="form-group">
        <label className="form-label">Location</label>
        <input
          type="text"
          className="form-input"
          value={formData.location || ''}
          onChange={(e) => setFormData({ ...formData, location: e.target.value })}
          placeholder="City, State"
        />
      </div>
      <div className="form-group">
        <label className="form-label">LinkedIn</label>
        <input
          type="url"
          className="form-input"
          value={formData.linkedin || ''}
          onChange={(e) => setFormData({ ...formData, linkedin: e.target.value })}
          placeholder="https://linkedin.com/in/yourprofile"
        />
      </div>
      <div className="form-group">
        <label className="form-label">Portfolio/Website</label>
        <input
          type="url"
          className="form-input"
          value={formData.website || ''}
          onChange={(e) => setFormData({ ...formData, website: e.target.value })}
          placeholder="https://yourportfolio.com"
        />
      </div>
    </div>
  )

  const renderSummaryForm = () => (
    <div className="form-group">
      <label className="form-label">Professional Summary</label>
      <textarea
        className="form-textarea"
        value={formData || ''}
        onChange={(e) => setFormData(e.target.value)}
        placeholder="Write a compelling professional summary highlighting your key achievements and skills..."
        rows={6}
      />
      <div className="form-help">
        <small>2-3 sentences that highlight your most relevant experience and achievements.</small>
      </div>
    </div>
  )

  const renderExperienceForm = () => {
    const experiences = Array.isArray(formData) ? formData : []

    const addExperience = () => {
      const newExp = {
        position: '',
        company: '',
        duration: '',
        location: '',
        description: '',
        achievements: []
      }
      setFormData([...experiences, newExp])
    }

    const updateExperience = (index, field, value) => {
      const updated = [...experiences]
      updated[index] = { ...updated[index], [field]: value }
      setFormData(updated)
    }

    const removeExperience = (index) => {
      const updated = experiences.filter((_, i) => i !== index)
      setFormData(updated)
    }

    return (
      <div className="experience-form">
        {experiences.map((exp, index) => (
          <div key={index} className="experience-item-form">
            <div className="form-header">
              <h4>Experience {index + 1}</h4>
              <button
                type="button"
                className="btn-icon btn-danger"
                onClick={() => removeExperience(index)}
              >
                <FiTrash2 />
              </button>
            </div>
            <div className="form-grid">
              <div className="form-group">
                <label className="form-label">Position</label>
                <input
                  type="text"
                  className="form-input"
                  value={exp.position || ''}
                  onChange={(e) => updateExperience(index, 'position', e.target.value)}
                  placeholder="Software Engineer"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Company</label>
                <input
                  type="text"
                  className="form-input"
                  value={exp.company || ''}
                  onChange={(e) => updateExperience(index, 'company', e.target.value)}
                  placeholder="Company Name"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Duration</label>
                <input
                  type="text"
                  className="form-input"
                  value={exp.duration || ''}
                  onChange={(e) => updateExperience(index, 'duration', e.target.value)}
                  placeholder="Jan 2020 - Present"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Location</label>
                <input
                  type="text"
                  className="form-input"
                  value={exp.location || ''}
                  onChange={(e) => updateExperience(index, 'location', e.target.value)}
                  placeholder="New York, NY"
                />
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Description & Achievements</label>
              <textarea
                className="form-textarea"
                value={exp.description || ''}
                onChange={(e) => updateExperience(index, 'description', e.target.value)}
                placeholder="Describe your key responsibilities and achievements..."
                rows={4}
              />
            </div>
          </div>
        ))}
        <button type="button" className="btn btn-outline" onClick={addExperience}>
          <FiPlus /> Add Experience
        </button>
      </div>
    )
  }

  const renderEducationForm = () => {
    const education = Array.isArray(formData) ? formData : []

    const addEducation = () => {
      const newEdu = {
        degree: '',
        school: '',
        year: '',
        location: '',
        gpa: '',
        honors: ''
      }
      setFormData([...education, newEdu])
    }

    const updateEducation = (index, field, value) => {
      const updated = [...education]
      updated[index] = { ...updated[index], [field]: value }
      setFormData(updated)
    }

    const removeEducation = (index) => {
      const updated = education.filter((_, i) => i !== index)
      setFormData(updated)
    }

    return (
      <div className="education-form">
        {education.map((edu, index) => (
          <div key={index} className="education-item-form">
            <div className="form-header">
              <h4>Education {index + 1}</h4>
              <button
                type="button"
                className="btn-icon btn-danger"
                onClick={() => removeEducation(index)}
              >
                <FiTrash2 />
              </button>
            </div>
            <div className="form-grid">
              <div className="form-group">
                <label className="form-label">Degree</label>
                <input
                  type="text"
                  className="form-input"
                  value={edu.degree || ''}
                  onChange={(e) => updateEducation(index, 'degree', e.target.value)}
                  placeholder="Bachelor of Science in Computer Science"
                />
              </div>
              <div className="form-group">
                <label className="form-label">School</label>
                <input
                  type="text"
                  className="form-input"
                  value={edu.school || ''}
                  onChange={(e) => updateEducation(index, 'school', e.target.value)}
                  placeholder="University Name"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Year</label>
                <input
                  type="text"
                  className="form-input"
                  value={edu.year || ''}
                  onChange={(e) => updateEducation(index, 'year', e.target.value)}
                  placeholder="2020"
                />
              </div>
              <div className="form-group">
                <label className="form-label">GPA (Optional)</label>
                <input
                  type="text"
                  className="form-input"
                  value={edu.gpa || ''}
                  onChange={(e) => updateEducation(index, 'gpa', e.target.value)}
                  placeholder="3.8/4.0"
                />
              </div>
            </div>
          </div>
        ))}
        <button type="button" className="btn btn-outline" onClick={addEducation}>
          <FiPlus /> Add Education
        </button>
      </div>
    )
  }

  // FIXED: Use newSkill and setNewSkill from top-level state
  const renderSkillsForm = () => {
    const skills = Array.isArray(formData) ? formData : []

    const addSkill = () => {
      if (newSkill.trim()) {
        setFormData([...skills, newSkill.trim()])
        setNewSkill('')
      }
    }

    const removeSkill = (index) => {
      const updated = skills.filter((_, i) => i !== index)
      setFormData(updated)
    }

    return (
      <div className="skills-form">
        <div className="skills-input">
          <input
            type="text"
            className="form-input"
            value={newSkill}
            onChange={(e) => setNewSkill(e.target.value)}
            placeholder="Add a skill..."
            onKeyPress={(e) => e.key === 'Enter' && addSkill()}
          />
          <button type="button" className="btn btn-primary" onClick={addSkill}>
            <FiPlus />
          </button>
        </div>
        <div className="skills-list">
          {skills.map((skill, index) => (
            <div key={index} className="skill-item">
              <span>{skill}</span>
              <button
                type="button"
                className="btn-icon btn-danger"
                onClick={() => removeSkill(index)}
              >
                <FiX />
              </button>
            </div>
          ))}
        </div>
      </div>
    )
  }

  const renderCertificationsForm = () => {
    const certifications = Array.isArray(formData) ? formData : []

    const addCertification = () => {
      const newCert = {
        name: '',
        issuer: '',
        year: '',
        url: ''
      }
      setFormData([...certifications, newCert])
    }

    const updateCertification = (index, field, value) => {
      const updated = [...certifications]
      updated[index] = { ...updated[index], [field]: value }
      setFormData(updated)
    }

    const removeCertification = (index) => {
      const updated = certifications.filter((_, i) => i !== index)
      setFormData(updated)
    }

    return (
      <div className="certifications-form">
        {certifications.map((cert, index) => (
          <div key={index} className="certification-item-form">
            <div className="form-header">
              <h4>Certification {index + 1}</h4>
              <button
                type="button"
                className="btn-icon btn-danger"
                onClick={() => removeCertification(index)}
              >
                <FiTrash2 />
              </button>
            </div>
            <div className="form-grid">
              <div className="form-group">
                <label className="form-label">Certification Name</label>
                <input
                  type="text"
                  className="form-input"
                  value={cert.name || ''}
                  onChange={(e) => updateCertification(index, 'name', e.target.value)}
                  placeholder="AWS Certified Solutions Architect"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Issuing Organization</label>
                <input
                  type="text"
                  className="form-input"
                  value={cert.issuer || ''}
                  onChange={(e) => updateCertification(index, 'issuer', e.target.value)}
                  placeholder="Amazon Web Services"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Year</label>
                <input
                  type="text"
                  className="form-input"
                  value={cert.year || ''}
                  onChange={(e) => updateCertification(index, 'year', e.target.value)}
                  placeholder="2023"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Verification URL (Optional)</label>
                <input
                  type="url"
                  className="form-input"
                  value={cert.url || ''}
                  onChange={(e) => updateCertification(index, 'url', e.target.value)}
                  placeholder="https://verify.certification.com"
                />
              </div>
            </div>
          </div>
        ))}
        <button type="button" className="btn btn-outline" onClick={addCertification}>
          <FiPlus /> Add Certification
        </button>
      </div>
    )
  }

  const renderProjectsForm = () => {
    const projects = Array.isArray(formData) ? formData : []

    const addProject = () => {
      const newProject = {
        name: '',
        description: '',
        technologies: [],
        url: '',
        github: ''
      }
      setFormData([...projects, newProject])
    }

    const updateProject = (index, field, value) => {
      const updated = [...projects]
      updated[index] = { ...updated[index], [field]: value }
      setFormData(updated)
    }

    const removeProject = (index) => {
      const updated = projects.filter((_, i) => i !== index)
      setFormData(updated)
    }

    return (
      <div className="projects-form">
        {projects.map((project, index) => (
          <div key={index} className="project-item-form">
            <div className="form-header">
              <h4>Project {index + 1}</h4>
              <button
                type="button"
                className="btn-icon btn-danger"
                onClick={() => removeProject(index)}
              >
                <FiTrash2 />
              </button>
            </div>
            <div className="form-grid">
              <div className="form-group">
                <label className="form-label">Project Name</label>
                <input
                  type="text"
                  className="form-input"
                  value={project.name || ''}
                  onChange={(e) => updateProject(index, 'name', e.target.value)}
                  placeholder="E-commerce Platform"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Live URL (Optional)</label>
                <input
                  type="url"
                  className="form-input"
                  value={project.url || ''}
                  onChange={(e) => updateProject(index, 'url', e.target.value)}
                  placeholder="https://myproject.com"
                />
              </div>
              <div className="form-group">
                <label className="form-label">GitHub URL (Optional)</label>
                <input
                  type="url"
                  className="form-input"
                  value={project.github || ''}
                  onChange={(e) => updateProject(index, 'github', e.target.value)}
                  placeholder="https://github.com/username/project"
                />
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Description</label>
              <textarea
                className="form-textarea"
                value={project.description || ''}
                onChange={(e) => updateProject(index, 'description', e.target.value)}
                placeholder="Describe your project and its key features..."
                rows={3}
              />
            </div>
          </div>
        ))}
        
        <button type="button" className="btn btn-outline" onClick={addProject}>
          <FiPlus /> Add Project
        </button>
      </div>
    )
  }

  return (
    <div className="editable-section">
      <div className="section-header">
        <h2>{sectionTitle}</h2>
        <div className="section-actions">
          <button className="btn btn-secondary" onClick={onCancel}>
            <FiX /> Cancel
          </button>
          <button className="btn btn-primary" onClick={handleSave}>
            <FiSave /> Save Changes
          </button>
        </div>
      </div>

      <div className="section-form">
        {renderForm()}
      </div>
    </div>
  )
}

function getDefaultData(sectionKey) {
  switch (sectionKey) {
    case 'personalInfo':
      return {
        name: '',
        email: '',
        phone: '',
        location: '',
        linkedin: '',
        website: ''
      }
    case 'summary':
      return ''
    case 'experience':
      return []
    case 'education':
      return []
    case 'skills':
      return []
    case 'certifications':
      return []
    case 'projects':
      return []
    default:
      return null
  }
}

export default EditableSection