import React from 'react';
import { useLocation } from 'react-router-dom';

function ViewPage() {
  const location = useLocation();
  const urlParams = new URLSearchParams(location.search);
  const content = urlParams.get('content') || 'No content available';

  return (
    <div className="view-page">
      <div className="view-container">
        <div className="brand-header">
          <h1>📄 QR Content</h1>
          <p className="subtitle">Successfully scanned from QR Code</p>
        </div>
        
        <div className="content-frame">
          <div className="content-display">
            <div className="content-text">
              {content}
            </div>
          </div>
        </div>
        
        <div className="footer-info">
          <div className="status-indicator">
            <span className="success-icon">✅</span>
            <span>Content loaded successfully</span>
          </div>
          <p>🔗 Generated by QR Code Generator</p>
        </div>
      </div>
    </div>
  );
}

export default ViewPage;
