import React from 'react';
import { useLocation } from 'react-router-dom';

function ViewPage() {
  const location = useLocation();
  const urlParams = new URLSearchParams(location.search);
  const content = urlParams.get('content') || 'No content available';

  return (
    <div className="view-page">
      <div className="view-container">
        <div className="brand-header">
          <h1>QR Code Content</h1>
          <p className="subtitle">Scanned from QR Code</p>
        </div>
        
        <div className="content-display">
          <div className="content-text">
            {content}
          </div>
        </div>
        
        <div className="footer-info">
          <p>📱 This content was accessed by scanning a QR code</p>
          <p>🔗 Generated by QR Code App</p>
        </div>
      </div>
    </div>
  );
}

export default ViewPage;
