// modernCardTemplate.js

export const generateModernCardCSS = (theme) => `
  /* Code Generated by Sidekick is for learning and experimentation purposes only. */
  body {
    font-family: ${theme.fontFamily};
    background: linear-gradient(135deg, ${theme.background} 60%, ${theme.accent} 100%);
    color: ${theme.text};
    margin: 0;
    min-height: 100vh;
  }
  .portfolio-container {
    max-width: 1100px;
    margin: 40px auto;
    padding: 2rem;
    background: rgba(255,255,255,0.95);
    border-radius: 24px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.12);
  }
  .section-title {
    font-size: 2.2rem;
    color: ${theme.primary};
    margin-bottom: 2rem;
    text-align: left;
    border-left: 6px solid ${theme.accent};
    padding-left: 1rem;
  }
  .about-section {
    display: flex;
    align-items: center;
    gap: 2rem;
    margin-bottom: 2rem;
  }
  .avatar {
    width: 120px;
    height: 120px;
    border-radius: 50%;
    background: ${theme.surface};
    object-fit: cover;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
  }
  .about-details {
    flex: 1;
  }
  .name {
    font-size: 2.5rem;
    font-weight: bold;
    color: ${theme.primary};
    margin-bottom: 0.5rem;
  }
  .title {
    font-size: 1.3rem;
    color: ${theme.secondary};
    margin-bottom: 1rem;
  }
  .bio {
    font-size: 1.1rem;
    color: ${theme.textSecondary};
    margin-bottom: 1rem;
  }
  .skills-container {
    display: flex;
    flex-wrap: wrap;
    gap: 0.7rem;
  }
  .skill {
    background: ${theme.accent};
    color: white;
    padding: 0.5rem 1rem;
    border-radius: 16px;
    font-size: 0.95rem;
    font-weight: 500;
  }
  .projects-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 2rem;
  }
  .project-card {
    background: ${theme.surface};
    border-radius: 16px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.08);
    padding: 1.5rem;
    transition: box-shadow 0.2s;
  }
  .project-card:hover {
    box-shadow: 0 8px 32px rgba(0,0,0,0.14);
  }
  .project-title {
    font-size: 1.4rem;
    color: ${theme.primary};
    margin-bottom: 0.5rem;
  }
  .project-description {
    color: ${theme.textSecondary};
    margin-bottom: 1rem;
  }
  .tech-container {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-bottom: 1rem;
  }
  .tech-tag {
    background: ${theme.primary};
    color: white;
    padding: 0.3rem 0.7rem;
    border-radius: 12px;
    font-size: 0.85rem;
    font-weight: 500;
  }
  .project-link {
    color: ${theme.accent};
    text-decoration: none;
    font-weight: 500;
  }
  .project-link:hover {
    text-decoration: underline;
  }
  .experience-list {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
  .experience-item {
    background: ${theme.surface};
    border-radius: 12px;
    padding: 1rem 1.5rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    border-left: 4px solid ${theme.primary};
  }
  .company {
    font-size: 1.2rem;
    font-weight: bold;
    color: ${theme.primary};
  }
  .position {
    font-size: 1rem;
    color: ${theme.secondary};
    margin-bottom: 0.3rem;
  }
  .duration {
    color: ${theme.textSecondary};
    font-size: 0.95rem;
    margin-bottom: 0.8rem;
  }
  .contact-section {
    background: ${theme.surface};
    border-radius: 16px;
    padding: 2rem;
    margin-top: 2rem;
    text-align: center;
    box-shadow: 0 4px 16px rgba(0,0,0,0.08);
  }
  .contact-grid {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 1.2rem;
    margin-top: 1rem;
  }
  .contact-item {
    background: ${theme.primary};
    color: white;
    padding: 0.8rem 1.2rem;
    border-radius: 12px;
    text-decoration: none;
    font-weight: 500;
    transition: background 0.2s;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  .contact-item:hover {
    background: ${theme.accent};
  }
  @media (max-width: 800px) {
    .portfolio-container { padding: 1rem; }
    .about-section { flex-direction: column; align-items: flex-start; }
    .projects-grid { grid-template-columns: 1fr; gap: 1rem; }
    .contact-grid { flex-direction: column; gap: 0.7rem; }
  }
`;

const generateModernCardAboutHTML = (section) => {
  const data = section.data;
  const skillsHTML = data.skills?.map(skill =>
    `<span class="skill">${skill}</span>`
  ).join('') || '';

  return `
    <div class="section about-section">
      ${data.avatar ? `<img src="${data.avatar}" class="avatar" alt="${data.name}'s avatar" />` : ''}
      <div class="about-details">
        <div class="name">${data.name || ''}</div>
        <div class="title">${data.title || ''}</div>
        <div class="bio">${data.bio || ''}</div>
        ${skillsHTML ? `<div class="skills-container">${skillsHTML}</div>` : ''}
      </div>
    </div>
  `;
};

const generateModernCardProjectsHTML = (section) => {
  const projects = section.data || [];
  const projectsHTML = projects.map(project => {
    const techHTML = project.technologies?.map(tech =>
      `<span class="tech-tag">${tech}</span>`
    ).join('') || '';
    return `
      <div class="project-card">
        <div class="project-title">${project.title || ''}</div>
        <div class="project-description">${project.description || ''}</div>
        ${techHTML ? `<div class="tech-container">${techHTML}</div>` : ''}
        ${project.link ? `<a href="${project.link}" class="project-link" target="_blank" rel="noopener noreferrer">View Project →</a>` : ''}
      </div>
    `;
  }).join('');
  return `
    <div class="section">
      <div class="section-title">${section.title}</div>
      <div class="projects-grid">${projectsHTML}</div>
    </div>
  `;
};

const generateModernCardExperienceHTML = (section) => {
  const experiences = section.data || [];
  const experienceHTML = experiences.map(exp => `
    <div class="experience-item">
      <div class="company">${exp.company || ''}</div>
      <div class="position">${exp.position || ''}</div>
      <div class="duration">${exp.duration || ''}</div>
      <div>${exp.description || ''}</div>
    </div>
  `).join('');
  return `
    <div class="section">
      <div class="section-title">${section.title}</div>
      <div class="experience-list">${experienceHTML}</div>
    </div>
  `;
};

const generateModernCardContactHTML = (section) => {
  const data = section.data;
  const contactItems = [];
  if (data.email) contactItems.push(`<a href="mailto:${data.email}" class="contact-item">📧 ${data.email}</a>`);
  if (data.phone) contactItems.push(`<a href="tel:${data.phone}" class="contact-item">📞 ${data.phone}</a>`);
  if (data.linkedin) contactItems.push(`<a href="${data.linkedin}" class="contact-item" target="_blank" rel="noopener noreferrer">💼 LinkedIn</a>`);
  if (data.github) contactItems.push(`<a href="${data.github}" class="contact-item" target="_blank" rel="noopener noreferrer">🐙 GitHub</a>`);
  if (data.website) contactItems.push(`<a href="${data.website}" class="contact-item" target="_blank" rel="noopener noreferrer">🌐 Website</a>`);
  return `
    <div class="section contact-section">
      <div class="section-title">${section.title}</div>
      <div class="contact-grid">${contactItems.join('')}</div>
    </div>
  `;
};

const generateModernCardHTML = (sections, theme) => {
  const sectionHTML = sections
    .filter(section => section.isVisible)
    .map(section => {
      switch (section.type) {
        case 'about': return generateModernCardAboutHTML(section);
        case 'projects': return generateModernCardProjectsHTML(section);
        case 'experience': return generateModernCardExperienceHTML(section);
        case 'contact': return generateModernCardContactHTML(section);
        // Add education/certifications if needed
        default: return '';
      }
    })
    .join('\n');
  return `
    <div class="portfolio-container">
      ${sectionHTML}
    </div>
  `;
};

export const generateModernCardHTMLExport = ({ sections, theme, title = 'My Portfolio' }) => {
  const css = generateModernCardCSS(theme);
  const html = generateModernCardHTML(sections, theme);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    ${css}
hellp
  </style>
</head>
<body>
  ${html}
</body>
</html>`;
};
